language: node_js
node_js:
  - "node"
before_script:
  - npm install -g tiddlywiki
script: cp static.info ./*wiki/tiddlywiki.info; tiddlywiki ./*wiki --build

after_success:
  - bash ./publish.sh

branches:
  only:
    - master
